---
layout: post
title: java的异常处理
tag:
   - java
   - java基础
---





## try catch finally

### 演示代码

```
package demo1.demo2;

import java.util.Arrays;

public class Test {

  public static void main(String[] args) {
    try {
      System.out.println(1/0);
      //这里return依然会执行finally代码
      return;
      //System.exit(0) 只有杀死java虚拟机时才可以不执行finally中的代码
    } catch (NoSuchFieldError e) {
      e.printStackTrace();
    }finally {
      System.out.println("执行finally");
    }
    System.out.println("hello");

  }

}

```

### 输出结果

> 执行finally
> Exception in thread "main" java.lang.ArithmeticException: / by zero
> 	at demo1.demo2.Test.main(Test.java:9)
>
> Process finished with exit code 1

### 总结

>try-catch-finally 中 只有杀死虚拟机退出程序才可以不执行finally中的代码否则无论如何都会执行 包括return
>
>如果catch中的

## try-catch-catch

### 演示代码

```java
public class Test {
  public static void main(String[] args) {
    try {
      System.out.println(1 / 0);
    } catch (ArithmeticException e) {
      e.printStackTrace();
    } catch (Exception e) {
      e.printStackTrace();
    }

  }
}


```

---

### 演示代码2

```java
package demo3;

public class Test {
  public static void main(String[] args) {
    try {
      System.out.println(1 / 0);
    } catch (ArithmeticException |SecurityException e) {
      e.printStackTrace();
    }
  }
}

```

>在jdk1.7之后多个异常可以使用  \| 连接

### 总结

> catch多个对应的异常进行处理
>
> 注意点:
>
> ==范围小的异常类写在前面，把范围大的异常类写在后面== 
>
> ==异常范围声明越小越好方便于开发人员解决问题==

## try-finally(不推荐)

> 将异常交由JVM进行处理，JVM处理异常后退出程序 
>
> finally中的代码即使发生异常也会执行

