---
layout: post
title: java的异常处理
tag:
   - java
   - java基础
---









## 异常的概念

> 1.概念:
>
> .异常概念:在程序中  执行不正确的流程 或者发生错误 就是异常
>
> 
>
> 

### 异常的体系



|    异常的名称    |                          异常的说明                          |
| :--------------: | :----------------------------------------------------------: |
|    Throwable     | 所有异常的直接父类或者是间接父类,必须是Throwable子类或者是自身的异常才需要进行处理 |
|      Error       | 表示非常严重的错误 一般都是由jvm抛出的错误,这种错误不需要进行处理,避免这种错误产生 |
|    Exception     |             表示不是非常严重的异常 必须进行处理              |
| RuntimeException |         表示是运行时异常,运行时异常编译器不进行检查          |

## 异常的分类

- 编译时异常:在编译期间 发生的异常就是编译时异常

- 运行时异常 :在程序运行期间 发生的异常 就是运行时异常

  

 编译时异常

![image-20220225102922307](https://gitee.com/oneadm/blog_picture/raw/master/img/202202260126357.png)

运行时异常

![image-20220225103000867](https://gitee.com/oneadm/blog_picture/raw/master/img/202202260126358.png)

## jvm 处理异常

>1. 在执行代码的时候 发生异常
>2. 将异常信息封装Throwable类中
>3. 如果自身不处理异常 则会返回给调用着 一层一层往上进行抛
>4. 如果对异常都不进行处理 则由JVM来进行处理
>5. 打印堆栈信息（异常信息） 终止程序

## Throwable

> 概念: 
>
> 1. Throwable类是Java语言中所有错误或异常 的超类
>
> 2. 有当对象是此类(或者子类之一)的实例时，才能通过Java虚拟机或者Java throw 句抛出
>
> 3. 两个子类的实例,Error 和 Exception ，通常用于指示发生了异常情况
>
> 4. 常用的方法
>
>    |          方法的名称           |           方法的描述            |
>    | :---------------------------: | :-----------------------------: |
>    | public void printStackTrace() |      在控制台打印堆栈信息       |
>    |  public String getMessage()   | 返回此throwable的详细消息字符串 |
>    |   public String toString()    |    返回此throwable的简短描述    |
>
>    
>
> 

## try catch finally

### 演示代码

```
package demo1.demo2;

import java.util.Arrays;

public class Test {

  public static void main(String[] args) {
    try {
      System.out.println(1/0);
      //这里return依然会执行finally代码
      return;
      //System.exit(0) 只有杀死java虚拟机时才可以不执行finally中的代码
    } catch (NoSuchFieldError e) {
      e.printStackTrace();
    }finally {
      System.out.println("执行finally");
    }
    System.out.println("hello");

  }

}

```

### 输出结果

> 执行finally
> Exception in thread "main" java.lang.ArithmeticException: / by zero
> 	at demo1.demo2.Test.main(Test.java:9)
>
> Process finished with exit code 1

### 总结

>try-catch-finally 中 只有杀死虚拟机退出程序才可以不执行finally中的代码否则无论如何都会执行 包括return
>
>如果catch中的异常不匹配抛出的异常 则异常交由JVM进行处理 finally的代码正常执行后退出程序

## try-catch-catch

### 演示代码

```java
public class Test {
  public static void main(String[] args) {
    try {
      System.out.println(1 / 0);
    } catch (ArithmeticException e) {
      e.printStackTrace();
    } catch (Exception e) {
      e.printStackTrace();
    }

  }
}


```

---

### 演示代码2

```java
package demo3;

public class Test {
  public static void main(String[] args) {
    try {
      System.out.println(1 / 0);
    } catch (ArithmeticException |SecurityException e) {
      e.printStackTrace();
    }
  }
}

```

>在jdk1.7之后多个异常可以使用  \| 连接

### 总结

> catch多个对应的异常进行处理
>
> 注意点:
>
> ==范围小的异常类写在前面，把范围大的异常类写在后面== 
>
> ==异常范围声明越小越好方便于开发人员解决问题==

## try-finally(不推荐)

> 将异常交由JVM进行处理，JVM处理异常后退出程序 
>
> finally中的代码即使发生异常也会执行

## 运行时异常与编译时异常

> 1. 编译时异常必须进行try-catch处理 
>
>    - 定义:编译时异常代表已经知道可能会发生的异常
>    - 读取一个文件 可能存在文件不存在等等已知可能所以这种将这种可能定义为编译时异常   从程序角度这些异常时必须要进行处理的 
>    - 例子：FileNotFoundException 文件不存在异常 
>    - 编译时异常即非运行时异常 Excepetion 
>    - 运行时异常可以不进行try-catch处理
>
>    - 定义:运行时异常名字上可以看出只有运行时才知道有没有异常 所以不需要声明抛出
>    - RuntimeException 及其子类为运行时异常
>
>    编译时异常与运行时异常一样 如果由JVM处理后将直接终止程序 
>
>    
>
>    